spring:
  application:
    name: culture-tea

  # DB ??
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# server port
server:
  port: 8080

service:
  jwt:
    access-expiration: 36000000000
    secret-key: ${JWT_SECRET}
